### ISSUE TITLE
Default to removing the tag

### ISSUE THREAD

**Issue by jaydenseric** [frontendr/babel-plugin-transform-compress-graphql#1]
It would be more useful if the `tagFunction` option by default was undefined, which would result in removing the `tagName` tag in the output, making the template string untagged.

The current default `String.raw` not only adds extra characters to a bundle, but it also has [gotchas regarding escapes](https://github.com/jaydenseric/fake-tag#why-not-stringraw).

**Comment by frontendr** [comment]
Hi Jayden,

Good idea! I think I'll make this change today or tomorrow.

**Comment by frontendr** [comment]
Changed as reported. The default `tagName` is now a blank string so the default behavior of the plugin is now to remove the tag if there is no existing binding of that tag. I'll release `1.2.0` later this evening.

Thanks, @jaydenseric for this suggestion!
