### ISSUE TITLE
Also support GraphQL commented template literals 

### ISSUE THREAD

**Issue by dburles** [frontendr/babel-plugin-transform-compress-graphql#3]
It would be great if it could also support GraphQL commented template literals.

```
const query = /* GraphQL */ `
  query { ... }
`;
```

**Comment by jaydenseric** [comment]
This would be really awesome, that way people using GraphQL frameworks like [`graphql-react`](https://github.com/jaydenseric/graphql-react) that don't require `gql` tags can use this transform without having to configure ESLint for an undefined `gql` global:

```json
{
  "globals": {
    "gql": "readonly"
  }
}
```

I just started using this transform today and it works great!

I had to find and replace `` /* GraphQL */ ` `` with `` gql` ``.

**Comment by frontendr** [comment]
Good idea! There already is a `compress-graphql.d.ts` which should be picked up by your editor but I doubt ESLint knows about it. I'll see what I can do if I have some spare time on my hands.

**Comment by frontendr** [comment]
Thanks @dburles for making this suggestion! I've just added it and released it with [`1.3.0`](https://www.npmjs.com/package/babel-plugin-transform-compress-graphql/v/1.3.0).

**Comment by jaydenseric** [comment]
@frontendr you're a total legend 🙌

It works great.

**Comment by dburles** [comment]
Awesome! thanks @frontendr
