### ISSUE TITLE
Broken number interpolation

### ISSUE THREAD

**Issue by jaydenseric** [frontendr/babel-plugin-transform-compress-graphql#4]
This input:

```js
const ONE = 1
const query = /* GraphQL */ `
  {
    a(b: ${ONE} c: true)
  }
`
```

Incorrectly results in this output:

```js
const ONE = 1;
const query = `{a(b:${ONE}c:true)}`;
```

Which results in a query with invalid syntax:

```graphql
{a(b:1c:true)}
```

This went unnoticed in my project for some time. GraphQL.js v15 no longer tolerates numbers being followed immediately with letters, and now the compressed queries are being rejected as having syntax errors:

- https://github.com/graphql/graphql-js/releases/tag/v15.0.0
- https://github.com/graphql/graphql-js/pull/2164
- https://github.com/graphql/graphql-spec/pull/601

I mistakenly thought at first this was a `graphql-query-compress` issue (https://github.com/rse/graphql-query-compress/issues/14); but it turns out to definitely be an issue with this babel plugin.

**Comment by frontendr** [comment]
Thanks for the report! Haven't had a project with this GraphQL version so haven't noticed it.

I'll have a look when I can.

**Comment by jaydenseric** [comment]
I still see the issue in v1.3.2…

**Comment by jaydenseric** [comment]
I think it's a problem when the arguments are on new lines:

```js
const ONE = 1

const query = /* GraphQL */ `
  {
    a(
      a: ${ONE}
      b: true
    )
  }
`
```

**Comment by frontendr** [comment]
That's odd as I've literally used your test case in the unit tests:

[see test case input](https://github.com/frontendr/babel-plugin-transform-compress-graphql/blob/master/test/fixtures/literal-variables.js)
```js
const ONE = 1;
const TWO = 2;
const queryWithSpace = /* GraphQL */ `{
  a(b: ${ONE} c: true)
}`;

const queryWithComma = /* GraphQL */ `{
  a(b: ${ONE}, c: true)
}`;

const queryWithTrailingVariable = /* GraphQL */ `{
  a(b: ${ONE} c: ${TWO})
}`;
```
Is converted to:

[see test case expected output](https://github.com/frontendr/babel-plugin-transform-compress-graphql/blob/master/test/fixtures/literal-variables.expected.js)
```js
"use strict";

const ONE = 1;
const TWO = 2;
const queryWithSpace = `{a(b:${ONE} c:true)}`;
const queryWithComma = `{a(b:${ONE},c:true)}`;
const queryWithTrailingVariable = `{a(b:${ONE} c:${TWO})}`;
```

I'll add another test with newlines

**Comment by frontendr** [comment]
Just checked and that also works:

```js
const queryWithNewlines = /* GraphQL */ `{
  a(
    b: ${ONE}
    c: true
  )
}`;
```
Is converted to:
```js
const queryWithNewlines = `{a(b:${ONE} c:true)}`;
```

Edit: See [this commit](https://github.com/frontendr/babel-plugin-transform-compress-graphql/commit/e22a61d51f7688fc216162e0059c948932d26a45)

**Comment by jaydenseric** [comment]
Here is the source:

<img width="574" alt="Screen Shot 2020-05-26 at 8 20 46 pm" src="https://user-images.githubusercontent.com/1754873/82889717-82643880-9f8e-11ea-9e8c-b08d17a5ac76.png">

Here is the result:

```graphql
fragment userArtworkConnection on UserArtworkConnection{page(cursor:$cursorArtwork limit:8ascending:false){hasNextPage cursorLast edges{node{id title price{format asCurrency{format(locale:"en-US")}}sold image{srcWebp:url(width:250height:250devicePixelRatio:3format:WEBP resourceHints:{preload:true})srcFallback:url(width:250height:250devicePixelRatio:3format:JPG)}}}}}fragment userGalleryConnection on UserGalleryConnection{page(cursor:$cursorGallery limit:8ascending:false){hasNextPage cursorLast edges{node{id name location{map(width:250height:150zoom:14pitch:55style:"mapbox/streets-v11" resourceHints:{preload:true})}}}}}query($userId:ID!,$cursorArtwork:ID,$cursorGallery:ID){user:node(id:$userId){... on User{name description{html(topHeadingLevel:2)}country{name emoji}region{name}gravatar(size:450,resourceHints:{preload:true})dateRegistered{relative}isAuthenticatedUser artworks{count ...userArtworkConnection}galleries{count ...userGalleryConnection}}}}
```

**Comment by jaydenseric** [comment]
It's working now! It was probably just some tooling aggressively caching Babel config or something. Pretty strange.

**Comment by frontendr** [comment]
I can only see the first part of that but

```js
const query = /* GraphQL */ `
  fragment a on b {
    page(
      c: $var
      d: ${ONE}
      e: false
    ) {
      hasNextPage
    }
  }
`;
```

Is converted to:
```js
const query = `fragment a on b{page(c:$var d:${ONE} e:false){hasNextPage}}`;
```

Are you sure you've upgraded correctly?

**Comment by frontendr** [comment]
> It's working now! It was probably just some tooling aggressively caching Babel config or something. Pretty strange.

Oh *pfew! Was starting to doubt myself 😄 

Thanks again  for the report!
