### ISSUE TITLE
Broken string interpolation

### ISSUE THREAD

**Issue by 1v4nx** [frontendr/babel-plugin-transform-compress-graphql#5]
When interpolating with alpha characters in between (e.g, fragments), we end up with the same issue as in #4.

**Input**
```
const fragName = 'name';
const fragType = 'type';

gql`
fragment ${fragName} on ${fragType} {
  id
  name
}
`
```
- [Repro link](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZgJwIYHMBySC2BTGBeGAcjC20IG4AoUSWRVAFQE8AHXAwqVsqylARwA2AA0r0UOMLAAkAb3EYcAXxjgYc8czYrZlGDACWAEz0wSOSksrCgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.3&externalPlugins=babel-plugin-transform-compress-graphql%401.3.2)

**Output**
``` `fragment${fragName} on${fragType}{id name}`;```

**Expected output**
``` `fragment ${fragName} on ${fragType}{id name}`;```

**Versions:**
 - Plugin version: v1.3.2

**Comment by 1v4nx** [comment]
@frontendr Any updates on this??

**Comment by frontendr** [comment]
@1v4nx Thanks for your PR! I've created release 1.3.3 which includes a fix for this using most of the same logic.
